class consulta:
    #CONSULTA PARA EL LOGIN
    nivelUser = "SELECT nivel FROM usuarios WHERE usuario =? AND contrasena=? AND estatus = 1"
    bloqueoUser = "SELECT id FROM usuarios WHERE usuario = ? AND nivel = 2"
    bloqueoContra = "SELECT id FROM usuarios WHERE contrasena = ? AND usuario = ? AND nivel = 2"
    userBloqueado = "SELECT id FROM usuarios WHERE usuario =? AND estatus = 2"
    obtenerDatosUsuario = "SELECT lideres.id, lideres.nombre, lideres.apellido, lideres.ubicacion, usuarios.id FROM usuarios JOIN lideres ON lideres_id = lideres.id WHERE usuarios.usuario = ?"
    guardarEntradaBitacora = "INSERT INTO bitacora VALUES (NULL, ?, NULL, ?)"
    bloquearUsuario = "UPDATE usuarios SET estatus = 2 WHERE usuario = ?"
    guardarSalidaBitacora = "UPDATE bitacora SET fechaSalida = ? WHERE fechaEntrada = ? AND usuarios_id = ?"

    #CONSULTAS PARA EL REGISTRO
    verficarUbicacion = "SELECT id FROM lideres WHERE ubicacion =?"
    verficarNumero = "SELECT id FROM lideres WHERE telefono =?"
    verificarCorreo = "SELECT id FROM lideres WHERE correo =?"
    verficarCedula = "SELECT id FROM lideres WHERE cedula =?"
    verificarNombreUsuario = "SELECT id FROM usuarios WHERE usuario =?"
    llenarPreguntas = "SELECT pregunta FROM preguntas"
    obtenerIdPregunta = "SELECT id FROM preguntas WHERE pregunta = ?"
    guardarRespuesta = "INSERT INTO respuestas VALUES (NULL, ?, ?)"
    obtenerIdRespuesta = "SELECT respuestas.id FROM respuestas JOIN preguntas ON preguntas_id = preguntas.id WHERE preguntas.id = ? AND respuestas.respuesta = ?"
    guardarLider = "INSERT INTO lideres VALUES (NULL, ?, ?, ?, ?, ?, ?)"
    obtenerIdLider = "SELECT id FROM lideres WHERE cedula = ?"
    guardarUsuario = "INSERT INTO usuarios VALUES (NULL, ?, ?, ?, ?, ?, 1)"

    #CONSULTAS PARA EL RECUPERAR
    verificarCedulaRecuperar = "SELECT preguntas.pregunta FROM usuarios JOIN lideres ON lideres_id = lideres.id JOIN respuestas ON respuesta_id = respuestas.id JOIN preguntas ON preguntas_id = preguntas.id WHERE lideres.cedula = ?"
    verificarRespuesta = "SELECT respuestas.respuesta FROM usuarios JOIN lideres ON lideres_id = lideres.id JOIN respuestas ON respuesta_id = respuestas.id JOIN preguntas ON preguntas_id = preguntas.id WHERE lideres.cedula = ?"
    obtenerIdCedulaRecuperar = "SELECT usuarios.id FROM usuarios JOIN lideres ON lideres_id = lideres.id WHERE lideres.cedula = ?"
    guardarCambiosContrasena = "UPDATE usuarios SET contrasena =? WHERE usuarios.id =?"

    #CONSULTAS PARA PRINCIPAL
    verificarJefesFamiliaCartas = "SELECT jefesf.id FROM jefesf JOIN lideres ON lideres_id = lideres.id WHERE lideres.id = ?"
    obtenerInfoJefesFamiliaCartas = "SELECT id, nombre, apellido, ci FROM jefesf WHERE lideres_id =?"

    verificarCedulaJefesFamilia = "SELECT jefesf.nombre, jefesf.apellido FROM jefesf WHERE jefesf.ci = ?"
    verificarTelefonoJefesFamilia = "SELECT id FROM jefesf WHERE telefono =?"
    verificarCorreoJefesFamilia = "SELECT id FROM jefesf WHERE correo =?"
    obtenerEmpresas = "SELECT empresa FROM empresas"
    obtenerTamanos = "SELECT tamano FROM tamanos"
    obtenerPicos = "SELECT pico FROM picos"

    guardarJefeFamilia = "INSERT INTO jefesf VALUES (NULL, ?, ?, ?, ?, ?, ?, 1)"
    obtenerIdJefeFamilia = "SELECT id FROM jefesf WHERE ci = ?"
    obtenerIdEmpresa = "SELECT id FROM empresas WHERE empresa =?"
    obtenerIdTamano = "SELECT id FROM tamanos WHERE tamano =?"
    obtenerIdPico = "SELECT id FROM picos WHERE pico =?"
    guardarCilindros = "INSERT INTO cilindros VALUES (NULL, ?, ?, ?, ?, ?, 1)"
    obtenerCilindrosJefeFamilia = "SELECT pedidos.id, cilindros.id, empresas.empresa, tamanos.tamano, picos.pico FROM pedidos JOIN cilindros ON cilindros_id = cilindros.id JOIN jefesf ON jefesf_id = jefesf.id JOIN empresas ON empresas_id = empresas.id JOIN tamanos ON tamanos_id = tamanos.id JOIN picos ON picos_id = picos.id WHERE jefesf.id = ? AND pedidos.archivos_id IS NULL"
    obtenerCilindrosRepetidos = "SELECT cilindros.id FROM pedidos JOIN cilindros ON cilindros_id = cilindros.id JOIN jefesf ON jefesf_id = jefesf.id WHERE jefesf.id =? AND pedidos.archivos_id IS NULL"
    mostrarCilindrosJefeFamilia = "SELECT cilindros.id, empresas.empresa, tamanos.tamano, picos.pico, cilindros.fechaAsignada FROM cilindros JOIN empresas ON empresas_id = empresas.id JOIN tamanos ON tamanos_id = tamanos.id JOIN picos ON picos_id = picos.id JOIN jefesf ON jefesf_id = jefesf.id WHERE jefesf.id = ? AND cilindros.estatus = 1"
    guardarCilindrosPedidos = "INSERT INTO pedidos VALUES (NULL, ?, ?, NULL)"

    eliminarCilindro = "UPDATE cilindros SET estatus = 2 WHERE id =?"
    editarCilindro = "SELECT empresas.empresa, tamanos.tamano, picos.pico FROM cilindros JOIN empresas ON empresas_id = empresas.id JOIN tamanos ON tamanos_id = tamanos.id JOIN picos ON picos_id = picos.id WHERE Cilindros.id = ?"
    guardarCambioCilindro = "UPDATE cilindros SET empresas_id =?, picos_id =?, tamanos_id =? WHERE id = ?"
    eliminarCilindroJornadaJefe = "DELETE FROM pedidos WHERE id =?"
    mostrarDatosJefe = "SELECT jefesf.nombre, jefesf.apellido, jefesf.ci, jefesf.telefono, jefesf.correo, lideres.ubicacion FROM jefesf JOIN lideres ON lideres_id = lideres.id  WHERE jefesf.id = ?"
    actualizarNombreJefe = "UPDATE jefesf SET nombre = ? WHERE id = ?"
    actualizarApellidoJefe = "UPDATE jefesf SET apellido = ? WHERE id = ?"
    #actualizarJefe = "UPDATE jefesf SET ci = ? WHERE id = ?"
    verificarCorreoEditar = "SELECT jefesf.nombre, jefesf.apellido FROM jefesf WHERE jefesf.correo = ?"
    actualizarCorreoJefe = "UPDATE jefesf SET correo = ? WHERE id = ?"
    verificarTelefonoEditar = "SELECT jefesf.nombre, jefesf.apellido FROM jefesf WHERE jefesf.telefono = ?"
    actualizarTelefonoJefe = "UPDATE jefesf SET telefono = ? WHERE id = ?"
    obtenerReportesPedidos = "SELECT pedidos.id, jefesf.ci, jefesf.nombre, jefesf.apellido, empresas.empresa, tamanos.tamano, picos.pico, pedidos.fechaAgregada FROM pedidos JOIN cilindros ON cilindros_id = cilindros.id JOIN jefesf ON jefesf_id = jefesf.id JOIN empresas ON empresas_id = empresas.id JOIN tamanos ON tamanos_id = tamanos.id JOIN picos ON picos_id = picos.id JOIN lideres ON lideres_id = lideres.id WHERE lideres.id =? AND pedidos.archivos_id IS NULL ORDER BY jefesf.ci ASC"
    eliminarCilindroJornada = "DELETE FROM pedidos WHERE id =?"
    mostrarDatosLider = "SELECT lideres.nombre, lideres.apellido, lideres.cedula, lideres.telefono, lideres.correo, lideres.ubicacion FROM lideres WHERE lideres.id = ?"
    actualizarNombreLider = "UPDATE lideres SET nombre = ? WHERE id = ?"
    actualizarApellidoLider = "UPDATE lideres SET apellido = ? WHERE id = ?"
    verificarTelefonoLider = "SELECT lideres.nombre, lideres.apellido FROM lideres WHERE lideres.telefono = ?"
    actualizarTelefonoLider =  "UPDATE lideres SET telefono = ? WHERE id = ?"
    verificarCorreoLider = "SELECT lideres.nombre, lideres.apellido FROM lideres WHERE lideres.correo = ?"
    actualizarCorreoLider = "UPDATE lideres SET correo = ? WHERE id = ?"
    #guardarSalidaBitacora
    #verificarGeneracion = "SELECT archivos.fechaGenerado FROM pedidos JOIN archivos ON archivos_id IS NOT NULL = archivos.id JOIN cilindros ON cilindros_id = cilindros.id JOIN jefesf ON jefesf_id = jefesf.id WHERE lideres_id = ? AND archivos.fechaGenerado = ?"
    verificarGeneracion = "SELECT archivos.id FROM pedidos JOIN archivos ON pedidos.archivos_id = archivos.id JOIN cilindros ON pedidos.cilindros_id = cilindros.id JOIN jefesf ON cilindros.jefesf_id = jefesf.id WHERE jefesf.lideres_id = ? AND archivos.fechaGenerado = ? LIMIT 1"
    verificarPedidos = "SELECT pedidos.id FROM pedidos JOIN cilindros ON cilindros_id = cilindros.id JOIN jefesf ON jefesf_id = jefesf.id WHERE jefesf.lideres_id = ? AND archivos_id IS NULL"

    #GENERAR EL PDF
    obtenerCostosCilindros = "SELECT costo FROM tamanos"
    obtenerJornadaArchivo = "SELECT pedidos.id, jefesf.ci, jefesf.nombre, jefesf.apellido, empresas.empresa, picos.pico, tamanos.tamano, tamanos.costo, pedidos.fechaAgregada FROM pedidos JOIN jefesf ON jefesf_id = jefesf.id JOIN cilindros ON cilindros_id = cilindros.id JOIN empresas ON empresas_id = empresas.id JOIN tamanos ON tamanos_id = tamanos.id JOIN picos ON picos_id = picos.id WHERE lideres_id =? AND pedidos.archivos_id IS NULL ORDER BY jefesf.ci ASC"
    guardarRutasArchivos = "INSERT INTO archivos VALUES (NULL, ?, ?)"
    obtenerIdArchivo = "SELECT id FROM archivos WHERE rutas = ? AND fechaGenerado = ?"
    asignarIdArchivo = "UPDATE pedidos SET archivos_id = ? WHERE id = ?"
    obtenerHistorial = "SELECT pedidos.id, jefesf.ci, jefesf.nombre, jefesf.apellido, empresas.empresa, tamanos.tamano, picos.pico, pedidos.fechaAgregada FROM pedidos JOIN jefesf ON jefesf_id = jefesf.id JOIN cilindros ON cilindros_id = cilindros.id JOIN empresas ON cilindros.empresas_id = empresas.id JOIN tamanos ON tamanos_id = tamanos.id JOIN picos ON picos_id = picos.id JOIN lideres ON lideres_id = lideres.id WHERE archivos_id = ? ORDER BY jefesf.ci ASC"
    obtenerIdArchivos = "SELECT archivos_id FROM pedidos JOIN archivos ON archivos_id IS NOT NULL = archivos.id JOIN cilindros ON cilindros_id = cilindros.id JOIN jefesf ON jefesf_id = jefesf.id JOIN lideres ON lideres_id = lideres.id WHERE lideres_id = ? GROUP BY archivos_id"
    obtenerFechasJornadas = "SELECT fechaGenerado, id FROM archivos WHERE id = ?"
    origenRutaArchivo = "SELECT rutas FROM archivos WHERE id = ?"

    #LIDER POLITICO
    obtenerDatosLiderPolitico = "SELECT lideres.nombre, lideres.apellido, lideres.cedula, lideres.ubicacion, preguntas.pregunta, respuestas.respuesta, usuarios.usuario, usuarios.contrasena, lideres.telefono, lideres.correo FROM usuarios JOIN respuestas ON respuesta_id = respuestas.id JOIN preguntas ON preguntas_id = preguntas.id JOIN lideres ON lideres_id = lideres.id WHERE lideres.id = ?"
    obtenerTodosUsuarios = "SELECT lideres.nombre, lideres.apellido, lideres.cedula, lideres.id FROM usuarios JOIN lideres ON lideres_id = lideres.id WHERE usuarios.nivel = 2"
    obtenerDatosUsuarioLideresCalle = "SELECT lideres.nombre, lideres.apellido, lideres.cedula, lideres.ubicacion, preguntas.pregunta, respuestas.respuesta, usuarios.usuario, usuarios.contrasena, lideres.telefono, lideres.correo, usuarios.estatus FROM usuarios JOIN respuestas ON respuesta_id = respuestas.id JOIN preguntas ON preguntas_id = preguntas.id JOIN lideres ON lideres_id = lideres.id WHERE lideres.id = ?"
    actualizarEstatusUsuario = "UPDATE usuarios SET estatus = ? WHERE usuario = ?"
    actualizarPrecios = "UPDATE tamanos SET costo =? WHERE id = ?"
    verificarEmpresa = "SELECT empresa FROM empresas WHERE empresa = ?"
    guardarEmpresaNueva = "INSERT INTO empresas VALUES (NULL, ?)"
    verificarPico = "SELECT pico FROM picos WHERE pico = ?"
    guardarPicoNuevo = "INSERT INTO picos VALUES (NULL, ?)"
    extraerBitacora = "SELECT bitacora.fechaEntrada , bitacora.fechaSalida FROM bitacora JOIN lideres ON lideres_id = lideres.id JOIN usuarios ON usuarios_id = usuarios.id WHERE lideres.cedula = ?"
    obtenerArchivosId = "SELECT archivos_id FROM pedidos JOIN archivos ON archivos_id IS NOT NULL = archivos.id JOIN cilindros ON cilindros_id = cilindros.id JOIN jefesf ON jefesf_id = jefesf.id JOIN lideres ON lideres_id = lideres.id WHERE lideres.cedula = ? GROUP BY archivos_id"
    